### ISSUE TITLE
Warning: S3::putObject(): [InvalidAccessKeyId]

### ISSUE THREAD

**Issue by haleeben** [Flynsarmy/cloud-db-backup#1]
I've setup the backup.sh file to go to my Amazon S3 account but I get this error when running the cron job

Warning: S3::putObject(): [InvalidAccessKeyId] The AWS Access Key Id you provided does not exist in our records. in /home/bluemoun/cloud-db-backup-master/drivers/S3/s3.php on line 366

I've triple checked my access key and still get this error.

**Comment by Flynsarmy** [comment]
Give it a try now and let me know.

**Comment by haleeben** [comment]
Yep, that fixed it.
Thanks for the super fast response.

**Comment by haleeben** [comment]
Would there be a way to put the file in a folder in the bucket?

**Comment by Flynsarmy** [comment]
Open _/drivers/S3/backup.php_ and change

``` php
$key = basename($file);
```

to

``` php
$key = 'your_subfolder_name/'.basename($file);
```

**Comment by haleeben** [comment]
Fantastic, Thanks.
